# Generated by Django 3.2.6 on 2021-11-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211111_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Designation',
            field=models.CharField(blank=True, default='JE/C&W/TKD', max_length=30, null=True),
        ),
    ]
