# Generated by Django 3.2.6 on 2022-04-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Designation',
            field=models.CharField(blank=True, default='JE/CB', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Posted',
            field=models.CharField(blank=True, choices=[('Sickline Office', 'Sickline Office'), ('ROH Office', 'ROH'), ('Contract Office', 'Contract Office'), ('Tech Cell Office', 'Tech Cell Office'), ('OMRS Office', 'OMRS Office'), ('SSE Planning Office', 'SSE Planning Office'), ('M&P Section', 'M&P Section'), ('CB Administration', 'CB Administration'), ('Stores', 'Stores'), ('Wheel Shop', 'Wheel Shop')], default='Tech Cell Office', max_length=30, null=True),
        ),
    ]
