# Generated by Django 4.2.11 on 2024-04-21 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='LocoFailed',
        ),
    ]
