# Generated by Django 4.2.11 on 2024-04-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staff_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='TokenNumber',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
