# Generated by Django 4.2.11 on 2024-04-22 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staff_staffmobilenumber'),
        ('section', '0002_section_sectionincharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='SectionIncharge',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='staff.staff'),
            preserve_default=False,
        ),
    ]
