# Generated by Django 4.2.11 on 2024-04-30 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('repair', '0013_shedin_presentlocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShuntingNeededInLoco1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecordCreationDate', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('CompletionDate', models.DateTimeField(blank=True, null=True)),
                ('ShuntingStatus', models.BooleanField(blank=True, default=False)),
                ('ShuntingFile', models.FileField(blank=True, null=True, upload_to='Loco/%Y/%m/%d/')),
                ('ForJob', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repair.repairdetail')),
                ('From', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shuntfrom', to='locations.locations')),
                ('To', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shuntto', to='locations.locations')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shuntauth1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
