# Generated by Django 4.2.11 on 2024-04-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shunting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuntingneededinloco',
            name='CompletionDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
