# Generated by Django 4.2.11 on 2024-04-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shunting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shuntingneededinloco1',
            name='ShuntingStatus2',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
