# Generated by Django 4.2.11 on 2024-04-30 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shunting', '0002_shuntingneededinloco1_shuntingstatus2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shuntingneededinloco1',
            name='ShuntingStatus2',
        ),
    ]
