# Generated by Django 4.2.11 on 2024-04-22 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='MinorSchedule1',
            new_name='MajorSchedule10',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='MinorSchedule1Date',
            new_name='MajorSchedule10Date',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='MinorSchedule2',
            new_name='MajorSchedule11',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='MinorSchedule2Date',
            new_name='MajorSchedule11Date',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='MinorSchedule3',
            new_name='MajorSchedule8',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='MinorSchedule3Date',
            new_name='MajorSchedule8Date',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='MinorSchedule4',
            new_name='MajorSchedule9',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='MinorSchedule4Date',
            new_name='MajorSchedule9Date',
        ),
    ]
