# Generated by Django 4.2.11 on 2024-04-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holding', '0002_loco2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loco2',
            name='RecordCreationDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
