# Generated by Django 4.2.11 on 2024-04-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holding', '0003_alter_loco2_recordcreationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loco2',
            name='RecordCreationDate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
