# Generated by Django 4.2.11 on 2024-04-21 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holding', '0004_alter_loco2_recordcreationdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loco2',
            name='LocoCommDate',
        ),
        migrations.RemoveField(
            model_name='loco2',
            name='RecordCreationDate',
        ),
    ]
