# Generated by Django 4.2.11 on 2024-04-21 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('holding', '0005_remove_loco2_lococommdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loco2',
            name='LocoCommDate',
            field=models.DateField(default='1001-01-01', null=True),
        ),
        migrations.AddField(
            model_name='loco2',
            name='RecordCreationDate',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
