# Generated by Django 4.2.11 on 2024-04-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holding', '0006_loco2_lococommdate_loco2_recordcreationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loco2',
            name='LocoCommDate',
            field=models.DateField(null=True),
        ),
    ]
