# Generated by Django 4.2.11 on 2024-04-21 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holding', '0007_alter_loco2_lococommdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loco',
        ),
    ]
