# Generated by Django 4.2.11 on 2024-04-22 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0002_remove_staff_locofailed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OPR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('LocoFailureDate', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('LocoNumber', models.IntegerField(blank=True, null=True)),
                ('Div', models.CharField(blank=True, max_length=4, null=True)),
                ('Railway', models.CharField(blank=True, max_length=4, null=True)),
                ('Train', models.CharField(blank=True, max_length=15, null=True)),
                ('LocoType', models.CharField(blank=True, choices=[('SelectLoco', 'Please Select Loco Type'), ('WDG4', 'WDG4'), ('WDG4D', 'WDG4D'), ('WDP4', 'WDP4'), ('WDP4D', 'WDP4D'), ('WDP4B', 'WDP4B'), ('WDM3', 'WDM3'), ('WDM3D', 'WDM3D'), ('WDM3A', 'WDM3A'), ('WDG3A', 'WDG3A'), ('WDS6', 'WDS6'), ('WAP1', 'WAP1'), ('WAG7', 'WAG7'), ('WAG5', 'WAG5'), ('WAG11', 'WAG11'), ('WDS6AD', 'WDS6AD')], default='SelectLoco', max_length=11, null=True)),
                ('Shed', models.CharField(blank=True, max_length=6, null=True)),
                ('Load', models.CharField(blank=True, max_length=30, null=True)),
                ('Site', models.CharField(blank=True, max_length=30, null=True)),
                ('Section', models.CharField(blank=True, max_length=6, null=True)),
                ('detantion_time', models.CharField(blank=True, max_length=10, null=True)),
                ('LPName', models.CharField(blank=True, max_length=50, null=True)),
                ('LPHQ', models.CharField(blank=True, max_length=6, null=True)),
                ('LPCUG', models.CharField(blank=True, max_length=12, null=True)),
                ('LPExp', models.CharField(blank=True, max_length=40, null=True)),
                ('NCLI', models.CharField(blank=True, max_length=50, null=True)),
                ('LICUG', models.CharField(blank=True, max_length=6, null=True)),
                ('RelLocoNo', models.CharField(blank=True, max_length=6, null=True)),
                ('FailedLocoMove', models.CharField(blank=True, max_length=6, null=True)),
                ('FailedItem1', models.CharField(blank=True, max_length=6, null=True)),
                ('FailedItem2', models.CharField(blank=True, max_length=6, null=True)),
                ('SuspectedCauseOfFailure', models.CharField(blank=True, max_length=400, null=True)),
                ('LastFitOfFailedItem', models.CharField(blank=True, max_length=400, null=True)),
                ('HistoryOfSimilarFailure', models.CharField(blank=True, max_length=100, null=True)),
                ('SuspectedItemLastAttendedInShed', models.CharField(blank=True, max_length=400, null=True)),
                ('MakeOfSuspectedItem', models.CharField(blank=True, max_length=400, null=True)),
                ('CodalLifeOfFailureItem', models.DateTimeField(null=True)),
                ('FunctionOfThisItem', models.CharField(blank=True, max_length=400, null=True)),
                ('Responsibility', models.CharField(blank=True, max_length=400, null=True)),
                ('DisciplinaryAction', models.CharField(blank=True, max_length=400, null=True)),
                ('ActionTakenToAvoidInFuture', models.CharField(blank=True, max_length=400, null=True)),
                ('CLIReport', models.FileField(blank=True, null=True, upload_to='OPRCLIReport/%Y/%m/%d/')),
                ('FailureAvoidable', models.BooleanField(blank=True, default=False)),
                ('FailLocoFile', models.FileField(blank=True, null=True, upload_to='FailLocoFile/%Y/%m/%d/')),
                ('LocoFailureDetails', models.CharField(blank=True, max_length=2000, null=True)),
                ('SupChk1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Supchk1', to='staff.staff')),
                ('SupChk2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Supchk2', to='staff.staff')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='oprAuth1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
