# Generated by Django 4.2.11 on 2024-04-22 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holding', '0008_delete_loco'),
        ('opr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opr',
            name='LocoNumber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OPRLocoNumber', to='holding.loco2'),
        ),
        migrations.AlterField(
            model_name='opr',
            name='detantion_time',
            field=models.TimeField(null=True),
        ),
    ]
