# Generated by Django 4.2.11 on 2024-04-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opr', '0003_alter_opr_detantion_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opr',
            name='CodalLifeOfFailureItem',
            field=models.DurationField(null=True),
        ),
    ]
