# Generated by Django 4.2.11 on 2024-04-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opr', '0004_alter_opr_codallifeoffailureitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opr',
            name='FailedItem1',
        ),
        migrations.AlterField(
            model_name='opr',
            name='CodalLifeOfFailureItem',
            field=models.DurationField(default='[1] [[00:]00:]00', null=True),
        ),
        migrations.AlterField(
            model_name='opr',
            name='detantion_time',
            field=models.DurationField(default='[1] [[00:]00:]00', null=True),
        ),
    ]
