# Generated by Django 3.2.6 on 2021-08-28 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='p',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(default='NULL', max_length=100, unique=True)),
                ('PL_Number', models.BigIntegerField(null=True, unique=True)),
                ('AAC', models.IntegerField(null=True)),
                ('Stock', models.IntegerField(null=True)),
                ('updateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('MAC', models.IntegerField(blank=True, default=0)),
                ('critical', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
