# Generated by Django 4.2.11 on 2024-04-27 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('section', '0003_alter_section_sectionincharge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repair', '0010_shedin_locofaildate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatNeedeInLoco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecordCreationDate', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('ReceiptDate', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('MaterialName', models.CharField(blank=True, max_length=50, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('MaterialReceived', models.BooleanField(blank=True, default=False)),
                ('LocoFile', models.FileField(blank=True, null=True, upload_to='Loco/%Y/%m/%d/')),
                ('ForJob', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repair.repairdetail')),
                ('FromSection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='section.section')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='matneededauth1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
