# Generated by Django 4.2.11 on 2024-04-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_rename_matneedeinloco_matneededinloco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matneededinloco',
            name='ReceiptDate',
            field=models.DateTimeField(null=True),
        ),
    ]
